# This file has magic strings that we later substitute out at Docker runtime

GOOGLE_API_KEY: "GOOGLE_API_KEY_REPLACE_ME"

ALGOLIA_INDEX_PREFIX: "ALGOLIA_INDEX_PREFIX_REPLACE_ME"
ALGOLIA_APPLICATION_ID: "ALGOLIA_APPLICATION_ID_REPLACE_ME"
ALGOLIA_READ_ONLY_API_KEY: "ALGOLIA_READ_ONLY_API_KEY_REPLACE_ME"

TYPESENSE_HOST: "TYPESENSE_HOST_REPLACE_ME"
TYPESENSE_PORT: "TYPESENSE_PORT_REPLACE_ME"
TYPESENSE_PROTOCOL: "TYPESENSE_PROTOCOL_REPLACE_ME"
TYPESENSE_API_KEY: "TYPESENSE_API_KEY_REPLACE_ME"
